### ISSUE TITLE
Can this be used for Raspberry Pi 3 Model B+?

### ISSUE THREAD

**Issue by raspberrybuster** [goodboytower/GoodBTS#3]
Hi! I wonder that is it possible for use Raspberry Pi 3 Model B+? Nonetheless, the biggest issue is actually that, how can this be used with the latest Raspberry Buster? I am not sure but I am very stuck.. For example, when I tried to install the repositories, there are many errors. Here:

sudo apt-get install git php5 bladerf libbladerf-dev libbladerf0 automake gcc g++ libusb-1.0-0 libusb-1.0-0-dbg libusb1-devel libusb-1.0-0-dev cmake doxygen kdoc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'php5' has no installation candidate
E: Unable to locate package libbladerf0
E: Unable to locate package libusb-1.0-0-dbg
E: Couldn't find any package by glob 'libusb-1.0-0-dbg'
E: Couldn't find any package by regex 'libusb-1.0-0-dbg'
E: Unable to locate package libusb1-devel
E: Unable to locate package kdoc

Secondly, when I tried to install yate and yatebts, this happens:

pi@raspberrypi:~ $ /home/pi/yate# ./autogen.sh
-bash: /home/pi/yate#: No such file or directory
pi@raspberrypi:~ $

I really need to use the Pi 3 model B + as this is the only model my college has and i am using this for my final year project. thank you so much for your help.

**Comment by goodboytower** [comment]
Hi Raspberrybuster, sorry for taking so long to get to your question.

For php5, have you tried sudo apt-get install php, and then seeing if php 7.4.5 will work?

For the ./autogen.sh, can you show the output of "ls -la /home/pi/yate"? You can also use the find command if you extracted it to a different destination.

**Comment by raspberrybuster** [comment]
dont worry bro! thanks for the tip, I've got it working yesterday by using pi 3 b. have a good day!

Sent from my U.S.Cellular© Smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
